version: "3.9"

services: 
  db:
    image: postgres
    volumes: 
    - ./data/db:/var/lib/postgresql/data
    environment: 
    - POSTGRES_DB = postgres
    - POSTGRES_USER = postgres
    - POSTGRES_PASSWORD = postgres

  web:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on: 
      -db 

# This uses the build in development server to run your application on port 8000. Do not use this in a production environment. For more information, see Django documentation.