# Generated by Django 3.0.10 on 2020-10-18 06:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, max_length=20)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('summary', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت')),
                ('status', models.CharField(choices=[('draft', 'در حال انتظار'), ('published', 'منتشر شده')], default='draft', max_length=60, verbose_name='وضعیت')),
                ('tag', models.CharField(choices=[('shop', 'فروشگاه'), ('customer', 'مشتری'), ('avatar', 'آگهی')], max_length=20)),
            ],
        ),
    ]
